// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBagy5VSzP3q7vUWsIojAygNUMwQpKIQ2c',
    appId: '1:232456469504:web:20c31cba40b2b3dce1ace5',
    messagingSenderId: '232456469504',
    projectId: 'farmdashr',
    authDomain: 'farmdashr.firebaseapp.com',
    databaseURL: 'https://farmdashr-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'farmdashr.firebasestorage.app',
    measurementId: 'G-6EYRCWTQ8Y',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCqeGVuONVp-lUMN-H2BRVtGSyR4tp8u7c',
    appId: '1:232456469504:android:80fcc7698aa6d049e1ace5',
    messagingSenderId: '232456469504',
    projectId: 'farmdashr',
    databaseURL: 'https://farmdashr-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'farmdashr.firebasestorage.app',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBagy5VSzP3q7vUWsIojAygNUMwQpKIQ2c',
    appId: '1:232456469504:web:54d72a7b3f17371ce1ace5',
    messagingSenderId: '232456469504',
    projectId: 'farmdashr',
    authDomain: 'farmdashr.firebaseapp.com',
    databaseURL: 'https://farmdashr-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'farmdashr.firebasestorage.app',
    measurementId: 'G-W00LTL20G9',
  );
}